airbrake/airbrake-ruby

- circle.yml
The build time went down from 04:52 to 02:57.
> Configure Circle CI 6x paralellism

- lib/airbrake-ruby/config.rb
- lib/airbrake-ruby/sync_sender.rb
- spec/config_spec.rb
- spec/sync_sender_spec.rb
Default values are Net::HTTP's.
> Support open_timeout and read_timeout

- .rubocop.yml
- Gemfile
- benchmarks/benchmark_helpers.rb
- lib/airbrake-ruby/async_sender.rb
- lib/airbrake-ruby/notice.rb
- spec/airbrake_spec.rb
* Updated Rubocop to the recent version
* Configured Style/MultilineMethodCallBraceLayout and
Style/MultilineHashBraceLayout
* Fixed their offences
> rubocop: fix offences of some cops

- CHANGELOG.md
- README.md
- lib/airbrake-ruby/version.rb
MINOR version bump because public API behaviour was slightly changed.
> Release v1.4.0

- CHANGELOG.md
- lib/airbrake-ruby/filters/keys_filter.rb
- spec/notifier_spec.rb
Fixes #114 (Context keys are not filtered)
> keys_filter: filter out individual user keys

- README.md
- lib/airbrake-ruby/notice.rb
- spec/notice_spec.rb
See discussion here why it is needed:
https://github.com/airbrake/airbrake/pull/650
> notice: add #stash

- circle.yml
See: https://github.com/sickill/rainbow/issues/48
> circle: fix failing build due to the rainbow gem issue

- lib/airbrake-ruby/notice.rb
- spec/airbrake_spec.rb
> follow up on deprecations and silence warnings during test run

- lib/airbrake-ruby/filter_chain.rb
- lib/airbrake-ruby/filters/gem_root_filter.rb
- lib/airbrake-ruby/filters/keys_blacklist.rb
- lib/airbrake-ruby/filters/keys_filter.rb
- lib/airbrake-ruby/filters/keys_whitelist.rb
- lib/airbrake-ruby/filters/root_directory_filter.rb
- lib/airbrake-ruby/filters/system_exit_filter.rb
- lib/airbrake-ruby/filters/thread_filter.rb
- lib/airbrake-ruby/notifier.rb
- spec/filter_chain_spec.rb
* filter_chain: rename 'keys_filters' to 'post_filters' 
* filter_chain: sort filters by weight
> filter_chain: refactor code

- spec/filters/thread_filter_spec.rb
Fixes:
https://circleci.com/gh/airbrake/airbrake-ruby/787#tests/containers/5
> filters/thread_filter_spec: isolate thread data per test

- lib/airbrake-ruby/notifier.rb
commonize method interface NilNotifier and Notifier.
> commonize method NilNotifier.

- lib/airbrake-ruby/response.rb
- spec/notifier_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/775
(Airbrake: unexpected code (420))
> response: handle error 420

- CHANGELOG.md
- lib/airbrake-ruby/notice.rb
- spec/notice_spec.rb
Replaces https://github.com/airbrake/airbrake-ruby/pull/247
> notice: append $PROGRAM_NAME to environment

- lib/airbrake-ruby/filters/keys_blacklist.rb
- lib/airbrake-ruby/filters/keys_filter.rb
- lib/airbrake-ruby/filters/keys_whitelist.rb
Hello,
I was integrating Airbrake on a project which required some filtering to be done and ran into a small issue. The sample code in the code blocks didn't match what was implemented. It's not a huge difference but thought it'd be helpful if it was updated for new users.
> Update code doc blocks to reflect initialize method from KeysFilter

- CHANGELOG.md
- benchmarks/truncator.rb
- benchmarks/truncator_string_encoding.rb
- lib/airbrake-ruby/notice.rb
- lib/airbrake-ruby/truncator.rb
- spec/fixtures/project_root/code.rb
- spec/truncator_spec.rb
Fixes #281 (Frozen hashes breaking truncator functionality)
> Refactor Truncator to not mutate objects

- CHANGELOG.md
- README.md
- lib/airbrake-ruby/filter_chain.rb
- spec/airbrake_spec.rb
- spec/notifier_spec.rb
Fixes #290 (Add the ability to disable filters)
> filter_chain: don't add ThreadFilter by default

- README.md
Pointed in
https://github.com/airbrake/airbrake/issues/696#issuecomment-384778353
> README: fix example

- spec/airbrake_spec.rb
- spec/async_sender_spec.rb
- spec/notice_spec.rb
- spec/notifier_spec.rb
- spec/response_spec.rb
- spec/sync_sender_spec.rb
This is a major refactoring. The specs in this project need some love and some restructuring. The problem is that `notifier_spec` and `airbrake_spec` have some overlap and `airbrake_spec` doesn't really reflect the layer it tests.
> Refactor specs

- spec/filters/keys_whitelist_spec.rb
With help of #324 I established that MRI 2.3 & 2.4 choke on the recursive hash
example on Circle CI. Example build:
https://circleci.com/workflow-run/c112358c-e7bf-4789-9eb2-4891ea84da68
It seems like a bug in the interpreter, which was fixed in 2.5, so we can ignore
the example on 2.3 & 2.4 (although it passes locally for me on 2.4 each time).
> spec/filters/keys_whitelist: fix sporadic segfault

- lib/airbrake-ruby/query_notifier.rb
- lib/airbrake-ruby/route_notifier.rb
Looks like this is not used anywhere and I cannot really remember why exactly I
wanted it.
> {query,route}_notifier: don't set Thread name

- CHANGELOG.md
- lib/airbrake-ruby.rb
- lib/airbrake-ruby/config.rb
- lib/airbrake-ruby/deploy_notifier.rb
- lib/airbrake-ruby/notice_notifier.rb
- lib/airbrake-ruby/performance_notifier.rb
- spec/config_spec.rb
> Remove deprecated functionality

- lib/airbrake-ruby.rb
No need for hashes anymore since this wraps 1 notifier only.
> airbrake-ruby: simplify internal API

- .rubocop.yml
- spec/airbrake_spec.rb
- spec/backtrace_spec.rb
- spec/config/validator_spec.rb
- spec/config_spec.rb
- spec/deploy_notifier_spec.rb
- spec/filters/git_repository_filter.rb
- spec/notice_notifier_spec.rb
- spec/notice_notifier_spec/options_spec.rb
- spec/notice_spec.rb
- spec/sync_sender_spec.rb
- spec/tdigest_spec.rb
- spec/truncator_spec.rb
> rubocop: stop enforcing Layout/DotPosition

- .gitignore
- Gemfile
- spec/notice_notifier_spec.rb
- spec/notice_notifier_spec/options_spec.rb
- spec/performance_notifier_spec.rb
- spec/spec_helper.rb
I see value in this tool because it helps me doing TDD. It's not essential (code
coverage is already above 90%) but it's a nice additional (and optional) check.
> Depend on simplecov and configure it

- lib/airbrake-ruby.rb
- lib/airbrake-ruby/config.rb
- lib/airbrake-ruby/loggable.rb
- lib/airbrake-ruby/notice_notifier.rb
* fixed invalid/missing macro names
* fixed unknown params for `attr_*`
> Fix errors in YARD documentation

- .circleci/config.yml
- airbrake-ruby.gemspec
This should fail the build if there are errors in the documentation.
> circleci/config: add 'yard_lint' job

- lib/airbrake-ruby/async_sender.rb
This way we don't launch unused threads for customers who don't use APM.
> async_sender: delay thread pool instantiation

- .circleci/config.yml
> circleci: use Ruby 2.7 instead of 2.7.0

- .circleci/config.yml
- CHANGELOG.md
- README.md
> Drop support for Ruby 2.1

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
- README.md
- airbrake-ruby.gemspec
- lib/airbrake-ruby/filters/keys_filter.rb
Fixes https://github.com/airbrake/airbrake-ruby/issues/600
> Drop support for Ruby 2.2

- .github/workflows/test.yml
Similar to: https://github.com/airbrake/airbrake/pull/1217
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
> .github/workflows/test: set read permissions on contents

- lib/airbrake-ruby/async_sender.rb
We don't log anything in this class.
> async_sender: do not include Loggable

- .github/workflows/test.yml
Format with Prettier and update actions that used to be commented out.
> Brush up .github/workflows/test.yml

- README.md
Resolves #704
(sanitize_hash in KeysFilter may leak sensitive blocklisted params)
> README: clarify how filtering works
