airbrake/airbrake-ruby

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Sometimes exceptions can contain manual backtraces that quack similar to
Ruby exceptions, but do not stricly adhere their template. I stumbled
upon this issues, when I was working with SCSS. It sets a couple of
custom first frames such as:
```
Sass::SyntaxError: Undefined mixin 'animation'.
/home/app/assets/stylesheets/error_pages.scss:139:in `animation'
/home/app/app/assets/stylesheets/error_pages.scss:139
```
Previously, we were not able to parse the second frame.
Furthermore, we now raise error if we cannot parse a stack frame to
simplify debugguging and improving our parser.
=> backtrace: add support for generic backtraces

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes #8 (add_filter throwing exception)
=> airbrake-ruby: fix add_filter block API

spec/notifier_spec.rb
The previous regex failed to match OS values containing a `.` such as
`x86_64-darwin14.0`, causing the test to fail on such systems.
=> Fix OS match regex

CHANGELOG.md, lib/airbrake-ruby.rb
Fixes #13 (Unnecessary airbrake error when running unknown rake task)
The problem with Rake is that on unknown task it
[raises SystemExit][1] with help of [`Kernel.exit`][2], which we catch
and try to send to Airbrake, which results in an Airbrake::Error.
This is the easiest fix. I tried messing with the airbrake gem to load
the Airbrake config when you launch a Rake task inside a Rails app, but
it's not easy to do: the Rails app is not initialised at that moment.
I stopped digging there, because I was getting into the rabbit hole.
[1]: https://github.com/ruby/rake/blob/805c13ab52eae9df55f9030f40c7fbc1beadc105/lib/rake/application.rb#L191
[2]: http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-exit
=> airbrake-ruby: ignore SystemExit in the `at_exit` hook

README.md
Fixes #15 (Broken docs with '.add_filter' example --
notice[:error_class] didn't exists)
=> README: fix the add_filter example

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes #24 (Airbrake::Error - can't parse '/Users/grammakov/repositories
/weintervene/config.ru:in `new'')
=> backtrace: improve generic stackframe regexp

CHANGELOG.md, lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
In theory it's possible to generate a backtrace that consists only of
internal frames. When this happens, then we send a notice without a
backtrace, because all the internal frames are filtered. When we see a
notice without a backtrace in the dashboard, it's incredibly hard to
debug it.
This change ensures that in case of an internal error we at least can
debug the failure.
=> notifier: make sure generated notices always have a backtrace

CHANGELOG.md, lib/airbrake-ruby/async_sender.rb, lib/airbrake-ruby/notifier.rb, spec/async_sender_spec.rb, spec/notifier_spec.rb
Potentially fixes https://github.com/airbrake/airbrake/issues/463
(falling back to sync delivery because there are no running async
workers)
I noticed I can reliably reproduce this message when I invoke the Rails
console and manually send a notice via `Airbrake.notify`. It happens
because by default Rails launches [Spring][1], which preloads the app
by using the `fork()` system call. And when that happens, as we know,
our worker threads die.
The fix is simply to respawn workers. It works reliably with the Rails
console and I assume it will fix the above mentioned issue.
[1]: https://github.com/rails/spring/
=> notifier: respawn workers if they're all dead

lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes the build failure introduced by
https://circleci.com/gh/airbrake/airbrake-ruby/94
=> backtrace: handle empty functions

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, lib/airbrake-ruby/nested_exception.rb, spec/nested_exception_spec.rb
While working on https://github.com/airbrake/airbrake/pull/479 I
stumbled upon a bug in Airbrake Ruby where the default filter couldn't
process error payload because `:backtrace` was `nil`. Returning an
empty array in case the real backtrace is missing seems to be a more
secure approach.
=> nested_exception: fix backtrace parsing

CHANGELOG.md, lib/airbrake-ruby.rb
Fixes #28 ("Airbrake::Error: the 'default' notifier isn't configured"
thrown after unsuccessful specs)
This fixes issues with the Rake integration. There was a [similar
issue][1] to a bug with the Rake integration reported a couple of weeks
ago. The change presented here fixes both issues by reraising
`SystemExit`, which propagates it and gets handled by Ruby.
[1]: https://github.com/airbrake/airbrake-ruby/issues/13
=> airbrake-ruby: reraise SystemExit instead of raising Airbrak::Error

.rubocop.yml, .rubocop_todo.yml, benchmarks/payload_truncator.rb, benchmarks/payload_truncator_string_encoding.rb
It's a new cop introduced by
https://github.com/bbatsov/rubocop/pull/2583
=> rubocop: fix the Performance/TimesMap cop offenses

.rubocop.yml, .rubocop_todo.yml
This new cop was introduced by
https://github.com/bbatsov/rubocop/pull/2542
This feature makes strings immutable in MRI 2.3.0
=> rubocop: fix the Style/FrozenStringLiteralComment offenses

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice.rb, spec/notice_spec.rb
The hostname information has to be present in many of our integrations
from the Airbrake gem. This information is just too useful and it
should be retreived by default.
=> notice: attach hostname information by default

lib/airbrake-ruby/filters/keys_filter.rb, spec/notifier_spec.rb
I was having problems on Ruby 2.1.5 where airbrake would fail to report errors if the URL contained something like `bg_color=%23FF00FF` - filter_url_params would try to assign `url.query = "bg_color=#FF00FF"`, which raises URI::InvalidComponentError.
(Interestingly, ruby 2.2 no longer raises in this case)
WDYT?
=> Encode components in filter_url_params

lib/airbrake-ruby/async_sender.rb, spec/async_sender_spec.rb
SizedQueue blocks if the queue is full. I think this behaviour is completely unexpected in an asynchronous component.
I think it would be better to drop the error in this situation. I can picture 2 scenarios where this could happen and dropping the extra errors would make sense:
1. **The app is sending errors faster than Airbrake server can process them**. It may be due to a bug in the app or because the app is being flooded by some sort of bogus request, we don't want the app to block for this reason, we would like, if possible, to keep providing service even if it's with degraded performance. In this situation, still many errors will make it to the Airbrake server so we won't miss that something is wrong.
2. **The Airbrake server has a problem and is not accepting errors**. In this …
=> Asynchronous notifier shouldn't block if queue full

CHANGELOG.md, README.md, lib/airbrake-ruby/version.rb
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards
compatible functionality is introduced to the public API.
We introduced the `timeout` option in this release.
=> Release v1.1.0

CHANGELOG.md, lib/airbrake-ruby/filters/keys_blacklist.rb, lib/airbrake-ruby/filters/keys_filter.rb, lib/airbrake-ruby/filters/keys_whitelist.rb, spec/notifier_spec.rb
Users reported a bug when a string key would filter out other matching
keys. For example `Airbrake.blacklist_keys([:boom])` would also filter
out `:boombastic` key. The presented change makes sure that we compare
Strings and Symbols exactly.
=> filters: compare non-regexp keys exactly

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/notifier_spec.rb
A user reported that it's not possible to filter context/user. It's a
reasonable request given that the user information has been moved to
context recently.
=> filters: filter context payload

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notifier.rb, spec/config_spec.rb, spec/notifier_spec/options_spec.rb
Fixes #53 (Expose blacklist_keys and whitelist_keys as config options)
=> Refactor Airbrake.blacklist/whitelist_keys to be an option

circle.yml, lib/airbrake-ruby/async_sender.rb
The fix ensures that the build passes on newer Rubinius versions, which
fail with "NoMethodError: undefined method `join' on nil:NilClass." due
to (apparently) a race condition.
The fix is copied from https://github.com/puma/puma/pull/809.
=> circle: update Rubinius versions and fix build

lib/airbrake-ruby/sync_sender.rb, spec/sync_sender_spec.rb
This exception is generated when the asynchronous worker times out trying to connect to the Airbrake server, if it's not captured, the worker dies.
=> Captures all StandardError Exceptions at sync_sender

CHANGELOG.md, README.md, lib/airbrake-ruby.rb
Fixes #58 (Configuration setting for unhandled exceptions)
Although we delete this, it is still useful. Therefore, this
functionality is going to be moved to the Airbrake gem instead.
=> airbrake-ruby: don't report unhandled exceptions

lib/airbrake-ruby/sync_sender.rb
http_proxy and https_proxy are respected by default.
=> Don't change Net::HTTP's default of using the environment proxy

CHANGELOG.md, lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
A customer who wanted to use `notify_airbrake` from the `airbrake` gem
with own params couldn't see the params because they are never
appended. This commit fixes the bug, so you can use `notify_airbrake`
or the notify methods from this library as intended.
=> notifier: add the ability to append params when passing a Notice object

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/notifier_spec.rb
Fixes #69 (send_notice raises URI::InvalidURIError with invalid URIs)
We lose the ability to filter query params, but the good thing is that
we can deliver unmodified URL.
=> filters/keys_filter: ignore bad URLs 

lib/airbrake-ruby/payload_truncator.rb, spec/payload_truncator_spec.rb
This change fixes a `RuntimeError: can't modify frozen String` error that happens in Payload Truncator when a string with invalid characters is frozen
=> Correctly handle a frozen string with invalid characters

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/546
(Disable Airbrake when not configured?)
This is probably the most annoying thing about this library. People
often don't see the original error when we raise ours (the original
error becomes nested and it is hard to notice). Sometimes users also
want to disable Airbrake, but they can't do so because once the library
is required, it assumes that the user wants to configure it
immediately. So if you don't configure it, your app crashes.
The solution is to stop raising this error. If not the complaints, I
would probably leave it as is. The current behaviour makes a lot of
sense to me. However the amount of confusion is immense, so "we must
deal with it".
=> airbrake-ruby: return nil instead of raising error

README.md
A user reported that they were confused our examples don't work. Same
old problem here: the program finishes before our workers can finish
work, so we must wait for them.
=> README: fix asynchronous examples

CHANGELOG.md, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/sync_sender.rb, spec/notice_spec.rb, spec/payload_truncator_spec.rb, spec/sync_sender_spec.rb
Fixes #82 (Airbrake-ruby stuck in an infinite loop)
This is the first step to fix the problem. Firstly, we must identify
the bad payload piece, then we will be able to decide what to do next.
This PR at least fixes the infinite loop. Apparently we forget to
filter something, so we reduce truncator's `max_size` and eventually
it becomes `0`. This is a sign things went wrong, so we can return
early.
=> notice: fix infinite loop when truncating payload

CHANGELOG.md, lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/notifier.rb, spec/notifier_spec/options_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/554 (Pipeline + React
stopping Airbrake with non-descript Error instead of Explanitory Rails
Error.)
We want to return as early as possible, so we don't try to parse the
given exception, which ensures we never have to deal with bad
backtraces.
=> notifier: don't try to construct a notice if the current env is ignored

CHANGELOG.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notifier.rb, spec/config_spec.rb
Fixes #80 (Airbrake: unexpected code (405). Body: Method Not Allowed)
and many other complains of people who are confused by the current
behaviour when we raise an error when they ignore current environment.
=> config: don't raise when current environment is ignored

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
It was a bad idea to restrict this option to Integers. People often
configure this option via ENV variables, so the value would be a
String.
=> config: allow setting String numbers as project_id

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
Fixes #91 (Airbrake being run on test and development environments)
This is not the first time someone is confused about this behaviour.
=> config: warn if ignore_environments is set, but environment isn't

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/558 (Airbrake
reports during rspec)
This is also a tiny wart, which confused many people. Relaxing this
restriction doesn't harm anyone.
=> config: do not rely on types when trying to compare environments

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, lib/airbrake-ruby/nested_exception.rb, lib/airbrake-ruby/notice.rb, spec/backtrace_spec.rb, spec/nested_exception_spec.rb
Fixes #98
(Airbrake throws away information for incompatible backtraces)
=> backtrace: add support for PL/SQL exceptions

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes #103 ("can't parse '#{stackframe}' (please file an issue so we
can fix " \")")
=> backtrace: add support for ExecJS backtraces

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
A user reported that they see a `NameError` with a Rails 3 and Ruby 1.9
app. The problem is that `Exception#cause` is not supported on
Ruby 1.9, so it needs special handling.
Also fixes Rubocop error about the Backtrace module being too long (refactored).
=> backtrace: fix ExecJS backtraces support for Ruby 1.9.3

README.md, lib/airbrake-ruby/notice.rb, spec/notice_spec.rb
Fixes #112 (Adding to the 'params' area of airbrake.io when
Airbrake.notify not explicitly called)
=> Add support for custom exception attributes

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/validator.rb, lib/airbrake-ruby/notifier.rb, spec/config/validator_spec.rb, spec/config_spec.rb, spec/notifier_spec.rb
Our dashboard expects it to be a String. Now we validate it and permit
only allowed types.
I also refactored the config class and extracted validation steps to a
separate class.
=> config: validate 'environment'

CHANGELOG.md, lib/airbrake-ruby/filter_chain.rb, spec/filter_chain_spec.rb
Fixes #117 (undefined method `sub!' for nil:NilClass)
The problem can be reproduced when airbrake-ruby tries to send an
exception with a backtrace, which couldn't be parsed. In that case we
put the whole frame into `function`, leaving `line` and `file` nil.
=> filter_chain: don't try to filter nil files

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes #116 (Can't parse crazy JRuby backtrace line)
=> backtrace: add support for JRuby classloaders

circle.yml
* Update all TEENY version of Rubies
* Test against JRuby 9.0.5.0
* Test against MRI 2.4.0-preview2
* Stop testing against Rubinius
This was a hard decision, but Rubinius is least stable Ruby
implementation. I am not even sure whether anybody uses it in
production. We often have build failures because of it. The nail in
the coffin is its current state. Out of thin air our [builds have
started failing on Rubinius][1]. The reason is that Rubinius wants a
modern LLVM. I've failed to configure it to use modern LLVM (was
getting some segfaults). Given little interest in this implementation
in the Ruby community and the amount of time I've spent to make it
work, I think moving on would be the best solution.
[1]: https://circleci.com/gh/airbrake/airbrake-ruby/468
=> circle: update rubies

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb
Fixes #123 (Delete deprecated methods)
=> notifier: delete deprecated {whitelist,blacklist}_keys methods

airbrake-ruby.gemspec
This eliminates all the Ruby warnings (finally).
=> gemspec: update the webmock gem

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/backtrace.rb
Fixes https://github.com/airbrake/airbrake/issues/609
(NoMethodError: undefined method `cause' - Airbrake 5.5.0 - Rails)
It was my oversight. I forgot that `Exception#cause` was introduced
only in Ruby 2.1.0.
=> backtrace: fix NoMethodError on Ruby 2.0.*

.rubocop.yml
Fixes failing build.
The cop was introduced by:
https://github.com/bbatsov/rubocop/commit/96f308b4f5601f4642fadc5c5e2826d90df0c0f5
=> rubocop: configure the new Metrics/BlockLength cop

CHANGELOG.md, README.md, lib/airbrake-ruby/filters/keys_blacklist.rb, lib/airbrake-ruby/filters/keys_whitelist.rb, lib/airbrake-ruby/notice.rb
This bug was present ever since we released v5. The context/notifier
payload was also appended to the root of the payload, so every notice
carried the same information twice. The API only wants context/notifier.
=> notice: don't send unwanted 'private' payload

airbrake-ruby.gemspec
So we can still test old Rubies.
=> gemspec: lock dependency on webmock v2.2.0

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes #139 (Found parsing error in my logs)
=> backtrace: special case classloader path

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
Fixes #144 (Can't reach a host with a subpath)
=> config: allow using URL slugs for 'host'

CHANGELOG.md, README.md, airbrake-ruby.gemspec, circle.yml, lib/airbrake-ruby.rb, lib/airbrake-ruby/backtrace.rb, lib/airbrake-ruby/payload_truncator.rb, spec/backtrace_spec.rb, spec/payload_truncator_spec.rb
* Remove support for 1.9.2 (official support ended on 2014-07-31)
* Remove support for 1.9.3 (official support ended on 2015-02-23)
* Remove support for JRuby 1.7.X (quote from JRuby: "The primary goal of
1.7 point releases is to fill out any missing compatibility issues
with Ruby 1.9.3)
=> Remove support for Ruby 1.9.2 & 1.9.3

.rubocop.yml
Fixes the following failure:
```
lib/airbrake-ruby/backtrace.rb:160:28:
C: Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
return true if frame =~ Patterns::EXECJS_SIMPLIFIED
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
It's a new cop. We cannot use its suggestion because we support older
rubies, which don't support the new method.
=> rubocop: disable Performance/RegexpMatch

airbrake-ruby.gemspec, spec/notifier_spec/options_spec.rb
I had a stale webmock and proxy tests were hanging on ruby-2.4.0. Newer
webmock adds support for ruby-2.4.0 and fixes tests.
Bonus change: these tests will now be raising a ThreadError in case this
error reoccurs in the future.
=> gemspec: set webmock to '~> 2.3'

CHANGELOG.md, lib/airbrake-ruby/notice.rb
This was needed to ease transition from v4 to v5, but now we don't
want to support this special case due to the ability to `build_notice`
and assign `component/action` to the notice directly. It was also
impossible to have `component/action` as a normal param key.
Deprecating it first, so it can be removed in the next release. I wasn't
careful enough, so some of our integrations use this legacy API.
=> notice: deprecate context/action compatibility code

CHANGELOG.md, README.md, lib/airbrake-ruby/version.rb
Next planned release is either `v1.7.1` (if we need minor fixups) or
`v2.0.0`, it'll remove the deprecated `component/action` API that we
deprecate in this release.
I know this is minor, but we want to adhere semver:
http://semver.org/#how-should-i-handle-deprecating-functionality
=> Release v1.7.0

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/filter_chain.rb, spec/filter_chain_spec.rb
Fixes #158 (blacklist_keys does not remove sensitive information from
post bodies)
This ensures that blacklist/whitelist filters always execute last.
Without this change blacklist/whitelist filtering is broken in
`airbrake` v5.7.0.
Since `8b8af2c77ea42b70b949e3b85df6cce3c977ee40` in `airbrake/airbrake`
Rack filters are being added after blacklist/whitelist filters, which
means Rack requests are never filtered.
In general, this change makes sure we blacklist/whitelist after all
permutations on a notice are done.
=> filter_chain: separate keys filters and execute them last

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb
Partially resolves #165 (Get rid of third argument in public API
methods)
=> airbrake-ruby: deprecate `notifier_name` argument

lib/airbrake-ruby/config.rb, spec/config_spec.rb
Many of our apps are deployed in symlinked root directories, for example: `/deploys/foo/current` which points to `/deploys/foo/releases/20170316121212`. Rubies backtraces always include the fully resolved path, for example '/deploys/foo/releases/20170316121212/app/models/foo.rb:12' ... so removing the symlinked root from it does not work and results in us reporting errors that cannot be grouped together.
Fix: resolve root to it's real path and the matching works.
(Tested that realpath works with strings and Pathnames)
=> resolve symlinked roots since that is what is shown in backtraces

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Fixes #183 (Can’t parse JRuby backtrace)
The problem is that that exception appears not to be subclassed from
`Java::JavaLang::Throwable` like all other JRuby exceptions, so our
algorithm returns a pattern for an MRI exception.
The fix is naive, but it still should cover most of the cases.
=> backtrace: fix JRuby exceptions support that are non-throwables

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, spec/airbrake_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/713
(undefined method `build_notice' for nil:NilClass)
It becomes really tedious to keep track of whether a notifier is
configured or not. Since we introduced `Airbrake.[]` to retrieve
notifiers, all integrations have to add an additional check for it:
```rb
if notifier = Airbrake[:default]
notifier.notify(...)
end
```
With the current change this check is not needed anymore.
=> airbrake-ruby,notifier: use the Null Object pattern for notifiers

lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
```ruby
URI.join("http://example.net/myapp/", "/api").to_s # => "http://example.net/api"
URI.join("http://example.net/myapp/", "api").to_s  # => "http://example.net/myapp/api"
```
`/myapp/` disappears when there is a slash
=> Fix capistrano airbrake:deploy task

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/filters/thread_filter.rb, spec/airbrake_spec.rb, spec/filters/thread_filter_spec.rb, spec/notifier_spec.rb, spec/notifier_spec/blacklist_keys_spec.rb, spec/notifier_spec/whitelist_keys_spec.rb
Fixes #187 (Save context of a current thread)
Replaces #194
Instead of providing an abstraction over `Thread.thread_variable_set`,
simply send everything we know about current thread.
=> Send thread information by default

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb
This simplifies public API, so users don't have to use `build_notice`
manually anymore. This change will be especially useful for setting
severity like this:
```ruby
Airbrake.notify('oops') do |notice|
notice[:context][:severity] = 'emergency'
end
```
=> notifier: make 'notify/notify_sync' accept a block

CHANGELOG.md, README.md, lib/airbrake-ruby/notice.rb, spec/notice_spec.rb
The link to the severity doc is handled by:
airbrake/airbrake-docs#115
=> notice: set context/severity to error and document severity

CHANGELOG.md, lib/airbrake-ruby/filters/thread_filter.rb, spec/filters/thread_filter_spec.rb
Fixes #204 (Airbrake gem segfaults on Circle CI)
I stumbled upon an edge case while running the thread filter against a
Rails app. The app would stuck because `io_obj.to_json` would never
return. The `io_obj` was open. Closed IO objects raise IOError, which
we already handle.
To make sure we avoid any kind of segfaults, we ignore
`:__recursive_key__`, which holds data for PrettyPrint.
=> filters/thread_filter: don't serialise IO objects

CHANGELOG.md, lib/airbrake-ruby/filters/thread_filter.rb, spec/filters/thread_filter_spec.rb
RSpec puts current example into a fiber variable. When we fetch it
and try to convert it to JSON with ActiveSupport's version of
`#to_json`, the library crashes with a `SystemStackError`.
The fix for this will probably be here:
https://github.com/rails/rails/issues/28996
=> filters/thread_filter: ignore the `__rspec` key

spec/filters/thread_filter_spec.rb
Fixes the following failures on JRuby:
https://circleci.com/gh/airbrake/airbrake-ruby/779#tests/containers/5
=> filters/thread_filter_spec: fix some examples on JRuby

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/filters/keys_blacklist_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/739
(Error Handler Threw An Error - Sidekiq)
=> filters/keys_filter: handle hash keys that are not symbols/strings

lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/notifier.rb, spec/filter_chain_spec.rb, spec/filters/gem_root_filter_spec.rb, spec/filters/keys_blacklist_spec.rb, spec/filters/root_directory_filter_spec.rb, spec/filters/system_exit_filter_spec.rb
`FilterChain` has tight coupling with `Airbrake::Config` without a good
reason. In this refactoring I uncouple it and append filters in the
`Notifier` class instead.
Bonus point: I refactored filter tests, and they're much easier to read
now.
=> filter_chain: simplify class and tests

CHANGELOG.md, lib/airbrake-ruby/filters/thread_filter.rb, spec/filters/thread_filter_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/743
(Airbrake.notify() broken)
Replaces: https://github.com/airbrake/airbrake-ruby/pull/223
This change makes `ThreadFilter` less useful, but more robust.
=> filters/thread_filter: whitelist allowed variable classes

lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
Related: https://github.com/airbrake/airbrake-ruby/pull/226
Before this change if a notice is ignored inside an `Airbrake.notify`
block, such notice would be sent with `null` body. This fix makes sure
that we don't send anything at all.
=> notifier: disallow sending of notices ignored inside notify blocks

CHANGELOG.md, lib/airbrake-ruby/filters/thread_filter.rb, spec/filters/thread_filter_spec.rb
Fixes #229 (Another segfault report)
Ruby segfaults whenever it tries to access `:__recursive_key__`.
Unfortunately, there's no other good way to avoid this segfault.
`:__recursive_key__` is set by PrettyPrint, so it's very common.
=> filters/thread_filter: fixed segfault on Ruby 2.1.3

lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
Ran into a problem in a recent Airbrake upgrade where a call to Airbrake.notify
was (unexpectedly!) mutating the params hash.
This is one approach to fix.
At various points in the filter call chains of building up an Airbrake
notice, the code mutates the params hash that is passed in (adding
keys like :priority and safe_level). A simple dup means the calling
code no longer has to worry about that params hash mutating.
=> Do a shallow copy of params hash in Notifier#build_notice

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb
This helper method is intended to simplify the following check:
```ruby
if Airbrake[:default].is_a?(Airbrake::NilNotifier)
end
```
With the new API it looks like this:
```ruby
if Airbrake.configured?
end
```
=> Implement `Airbrake#configured?`

CHANGELOG.md, lib/airbrake-ruby/response.rb, spec/notifier_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/768
(blank errors not reported)
The API response format has changed, so the library needs an adjustment.
=> response: fix parsing of errors

lib/airbrake-ruby/notice.rb
We don't reuse them, so there's no need for them to be separate
methods. Besides, this will decrease class length, so we don't introduce
any Rubocop offences
(https://github.com/airbrake/airbrake-ruby/pull/241)
=> notice: inline #[]= validation methods

.rubocop.yml, spec/backtrace_spec.rb
There's a new namespace called "Layout".
Fixes these warning:
```
.rubocop.yml: Style/DotPosition has the wrong namespace - should be Layout
.rubocop.yml: Style/IndentArray has the wrong namespace - should be Layout
.rubocop.yml: Style/IndentHeredoc has the wrong namespace - should be Layout
```
=> Fix Rubocop 0.49.1 warnings

README.md, lib/airbrake-ruby/notice.rb, spec/notifier_spec.rb
README shows following example to ignore ``StandardError``
```rb
Airbrake.add_filter do |notice|
if notice[:errors].any? { |error| error[:type] == 'StandardError' }
notice.ignore!
end
end
```
But we rarely raise ``StandardError`` itself.
Instead, we raise the descendants of ``StandardError``.
Current implementation converts the exception to a string value before filtering.
It looses class hierarchy.
This patch allows filter to use exception instance to do like this:
```rb
Airbrake.add_filter do |notice|
notice.ignore! if notice.exception.kind_of? StandardError
end
```
=> filter with raw exception instance

airbrake-ruby.gemspec
This fixes the following failure:
https://circleci.com/gh/airbrake/airbrake-ruby/889
=> gemspec: lock public_suffix to v2

airbrake-ruby.gemspec
v0.50 has a few bugs that prevent me from upgrading:
* https://github.com/bbatsov/rubocop/issues/4768
* https://github.com/bbatsov/rubocop/issues/4767
=> gemspec: lock rubocop to v0.49

.hound.yml
We use custom Rubocop rules and Hound can't see them. Inside the config we tell
Hound to respect our rules: https://houndci.com/configuration#ruby
=> Add hound.yml

.rubocop.yml, airbrake-ruby.gemspec, benchmarks/truncator_string_encoding.rb, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/response.rb, lib/airbrake-ruby/sync_sender.rb, spec/notifier_spec.rb, spec/spec_helper.rb, spec/truncator_spec.rb
* rubocop: don't enable already enabled [by default] cops
* rubocop: fix "wrong namespace" warnings
* rubocop: fix offences of the Naming/HeredocDelimiterNaming cop
=> Rubocop v0.50 fixes

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/filters/keys_blacklist_spec.rb
Fixes #256 (blacklist of HTTP_COOKIE does not work)
It wasn't possible to filter HTTP filters, but with this commit this is fixed.
=> filters/keys_filter: allow filtering HTTP headers

lib/airbrake-ruby/code_hunk.rb, spec/code_hunk_spec.rb, spec/notice_spec.rb
`nil` lines can happen when a backtrace contains file `config.ru` from
Rack. That frame doesn't carry line information.
Additionally, Rubocop was unhappy about the complexity of
`Airbrake::CodeHunk#get`, so I refactored it to make it simpler.
Tests were also leaking state because FileCache is global and we didn't nullify
it after every example. This is fixed now.
=> code_hunk: handle `nil` lines & refactor to please Rubocop

lib/airbrake-ruby/filters/gem_root_filter.rb
Mutating `file` with `GEM_ROOT` causes problems with code hunks. They rely on
the pristine value.
=> filters/gem_root: do not mutate file to avoid side effects

.rubocop.yml, Gemfile, airbrake-ruby.gemspec
* Gemfile: move rubocop from gemspec to Gemfile (Latest Rubocop doesn't support Ruby 2.0.0 anymore)
* rubocop: disable stupid rule of Gemspec/OrderedDependencies
=> Fix build failure

lib/airbrake-ruby/backtrace.rb
* backtrace: rename 'frame' to 'match' (this name is more accurate)
* backtrace: simplify #stack_frame
=> Refactor Backtrace

lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
`.start_with?` doesn't work and raise
`TypeError: no implicit conversion of Pathname into String`
=> backtrace: handle Pathname root_directory

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/notifier_spec/options_spec.rb
Fixes #276 (Specifying `blacklist_keys` with `whitelist_keys` can result in
error)
=> filters/keys: don't try to filter already filtered value

lib/airbrake-ruby/truncator.rb
As pointed out by
https://github.com/airbrake/airbrake-ruby/issues/281#issuecomment-342663451
the comment was misleading.
=> truncator: update comments for #truncate_object

CHANGELOG.md, lib/airbrake-ruby/truncator.rb, spec/truncator_spec.rb
Fixes #285 (Error in stackframe json)
=>  truncator: fix circular references

CHANGELOG.md, lib/airbrake-ruby/truncator.rb, spec/truncator_spec.rb
Additional fix for #285
("Cannot unmarshal string into Go struct field StackFrame.line" after truncating
big notices)
The problem is that `.include?` compares object hashes. For example, if we do
```
h1 = { a: 1 }
h2 = { a: 1 }
a = [h1, h2]
```
...then `h1 == h2`. Thus, if we truncate `a`, the truncator will incorrectly
mark them as circular. However, their object ids are different and they're not
really circular.
=> truncator: store and compare object ids instead of object hashes

.rubocop.yml, Gemfile, spec/airbrake_spec.rb, spec/notice_spec.rb, spec/promise_spec.rb
Every time Circle runs a build, it pulls the newest Rubocop. This causes
troubles for contributors and personally me. Instead of working on new features
or fixes we have to work on fixing Rubocop offences prior to merging actual
useful PRs. This happens because we used to specify an open-ended version
pattern for Rubocop in our Gemfile which was deliberate. Now it's obvious that
this approach isn't good.
With this change I lock Rubocop to a specific version, so it doesn't interrupt
anyone. I'll be updating Rubocop manually from time to time and fix offences in
a sweep.
=>  Gemfile: lock rubocop to v0.51.0 & fix offences

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
`config.code_hunks = false` had no effect. With this fix it's now possible to
disable code hunks.
=> backtrace: fix disabling of code hunks

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, spec/notifier_spec/options_spec.rb
Fixes https://github.com/airbrake/airbrake-ruby/issues/298
(Support for regex in 'ignore_environments')
=> airbrake-ruby/config: support Regexps for 'ignore_environments'

CHANGELOG.md, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb, spec/fixtures/project_root/vendor/bundle/ignored_file.rb
`vendor/bundle` needs to be blacklisted because if it's inside `root_directory`,
then code hunks are collected for every single frame (including gems).
The `vendor/bundle` path is not random. This is what Bundler docs say:
> Install your dependencies, even gems that are already installed to your system
> gems, to a location other than your system's gem repository. In this case,
> install them to vendor/bundle.
As result, some Heroku users may see code hunks for every single frame, which
often causes unwanted truncation of the notice.
=> backtrace: don't collect code hunks for files in vendor/bundle

lib/airbrake-ruby/filters/keys_filter.rb, spec/filters/keys_blacklist_spec.rb
Hi, 
The current specification does not apply a filter if array contains parameter of notification contents. This PR also filters even if the filter target parameter is in array.
=> Also filter the hash in the array with KeysBlacklist

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/filters/keys_blacklist_spec.rb
Fixes #308
(Change in 2.8.2 makes airbrake crash on error when filtering array
typed keys)
We should simply return non-hash values to make recursion stop failing.
=> filters/keys_filter: handle non-hash values

CHANGELOG.md, lib/airbrake-ruby/async_sender.rb
Fixes #312 (TypeError: can't move to the enclosed thread group)
`@workers.list.empty?` is racey, so if multiple threads are spawned at
the same time, one of them would spawn workers, the other one would
see that the list is empty, too and try to spawn the workers again.
I have to admit that storing the workers in a ThreadGroup instead of
an Array was a damn good choice. Luckily, it saved us from the worker
leak disaster.
=> async_sender: prevent race conditions in #has_workers?

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/filters/context_filter.rb, lib/airbrake-ruby/notifier.rb, spec/airbrake_spec.rb, spec/filters/context_filter_spec.rb, spec/notifier_spec.rb
Fixes #314 (Possible to set context for possible error?)
This feature has been request many times already. While Airbrake
supports it, it's not obvious for users how to make it work. It's also
hard to advertise it since there's no simple method to call to explain
the API. Previously, I used to link people to
https://github.com/airbrake/airbrake/issues/696#issuecomment-366857391
I guess it is not very convenient to use that API. Therefore, the feature
doesn't use Threads and is much simpler to use. Users no longer need to mess
with threads and cleaning up context information is on us.
=> Implement basic API for merging context

.rubocop.yml, Gemfile
* rubocop: disable the Naming/UncommunicativeMethodParamName cop
This rule is a little annoying to follow. Although I understand that it
prevents you from bad variable names, I am not ready to refuse from ingrained
names such as `th` or `ex` that we use in this codebase.
* rubocop: disable the Gemspec/RequiredRubyVersion cop
Rubocop doesn't support Ruby 2.0 but we still do. We simply cannot have the best
of both worlds (latest rubocop versions and old versions support), so I have to
disable it.
=> Gemfile: update rubocop to v0.55.0

lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb
It makes more sense to keep it there because that file is the only place where
it is used.
=> Move NilNotifier to airbrake-ruby.rb

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notice.rb, spec/config_spec.rb, spec/notice_spec.rb
We have been using `app_version` for tracking the user's app version. Since the
option expects a string there was no way to track any other
versions (dependencies is the most prominent example; version of Rails). We've
been using a hack where we prepend versions to the `app_version` value like this
'app/1.2.3 Rails/5.2.0`.
Those gloomy days are over with this new and shiny `versions` option. Now you
can attach any key and any value (please use names and versions respectively).
For example:
```ruby
config.versions = { 'bundler' => '1.2.3', 'Rails' => '5.2.0' }
```
=> Introduce the 'versions' option

.circleci/config.yml
It looks like with the new JRuby release the old CircleCI image is not available
anymore.
=> circleci: fix JRuby build

CHANGELOG.md, lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
`SyncSender` already handles that.
=> notifier: don't pass project id on `create_deploy` as a query param

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb, spec/notifier_spec.rb, spec/notifier_spec/options_spec.rb, spec/sync_sender_spec.rb
It's a simple renaming. This API doesn't introduce anything new.
=> Send errors to 'api.airbrake.io' instead of 'airbrake.io'

CHANGELOG.md, lib/airbrake-ruby/filters/git_revision_filter.rb
We shouldn't be reading files on every error. It's enough to read it once and
cache the result.
=> filters/git_revision: cache revision

spec/filters/git_last_checkout_filter_spec.rb
Circle uses the following email format: `circleci@123` (no dot), real emails use
`circleci@example.com`. Therefore, the test needs to know about this. Let's just
blame it on Circle.
=> spec/filters/git_last_checkout: fix flakey test

CHANGELOG.md, lib/airbrake-ruby/notifier.rb, spec/notifier_spec.rb
The order switch is needed to make inline filters usable in the ignore scenario.
Let's say we set notice's component in the inline filter. Then we define a
filter to ignore it via `Airbrake.add_filter`.
Before: `Airbrake.add_filter` filters are invoked. The inline filter is invoked
next. Nothing is ignored.
After: The inline filter is invoked. `Airbrake.add_filter` filters are reading
that and ignoring the notice.
This is exactly the problem with our Logger integration (it appears to be
impossible to ignore logger messages).
=> notifier: yield notice before filter_chain is invoked

README.md
=> README: remove the Travis badge

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/response.rb, lib/airbrake-ruby/route_sender.rb, lib/airbrake-ruby/sync_sender.rb, spec/airbrake_spec.rb, spec/async_sender_spec.rb, spec/config_spec.rb, spec/notifier_spec.rb, spec/response_spec.rb, spec/route_sender_spec.rb, spec/sync_sender_spec.rb
RouteSender aggregates information about requests and periodically sends
collected data to Airbrake.
The 'route_stats_flush_period' option allows:
* refactoring unit tests without messing with Airbrake Ruby's internals
* libraries that depend on airbrake-ruby can generate route stats
faster. Without this option there's no way to configure the delay, so every
time the user invokes this method, they have to wait 15 seconds for route
stats. With this option we can set it 0 and the request will be invoked
immediately
This feature is currently in beta and not available for everyone.
=> Implement RouteSender and Airbrake.inc_request

CHANGELOG.md, lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/notifier.rb, spec/filter_chain_spec.rb, spec/notifier_spec.rb, spec/spec_helper.rb
It has always bothered me that when you configure a notifier in Pry, it would
print a huge object state, which is barely readable. Quite often I would need to
exit pager with (q) to be able to type again.
With help of this change we get a meaningful inspect output, so only relevant
information is shown.
The default filter stuff was also moved from Notifier to FilterChain because
Rubocop was complaining that the Notifier class is too big.
=> notifier: implement #inspect and #pretty_print

airbrake-ruby.gemspec, lib/airbrake-ruby/response.rb, lib/airbrake-ruby/route_sender.rb, spec/response_spec.rb, spec/route_sender_spec.rb
https://github.com/tdunning/t-digest
> A new data structure for accurate on-line accumulation of rank-based
> statistics such as quantiles and trimmed means. The t-digest algorithm is also
> very parallel friendly making it useful in map-reduce and parallel streaming
> applications.
This introduces a few new dependencies:
```
tdigest (https://github.com/castle/tdigest)
|__rbtree (https://rubygems.org/gems/rbtree)
```
I am locking the `tdigest` dependency because it doesn't seem to follow
semver. It also is not in active development, so a sudden minor bump may break
Airbrake Ruby for a lot of customers. This is especially true since we
monkey-patch the class to pack tdigests how we need.
=> route_sender: replace min/max with TDigests

.circleci/config.yml, Gemfile, README.md, airbrake-ruby.gemspec, lib/airbrake-ruby.rb, lib/airbrake-ruby/backtrace.rb, spec/backtrace_spec.rb
Our newest dependency, `tdigest`, depends on `rbtree`. RBTree fails to compile
on 2.0.0p648: https://circleci.com/gh/airbrake/airbrake-ruby/2164
```
checking for rb_exec_recursive() in ruby.h... *** extconf.rb failed ***
...
/usr/local/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
```
There are some patches on the internet that fix RBTree mentioned in:
https://github.com/seki/Drip/issues/4
There's also RBTree 2, which may fix the problem:
https://github.com/kitak/rbtree2
That said, we don't control what `tdigest` depends on, so we don't have any
means to experiment.
Now, I'm usually reluctant to dropping Rubies without real need. In theory if we
controlled `tdigest`, we could still …
=> Drop support for Ruby 2.0

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/route_sender.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb, spec/route_sender_spec.rb
Also slightly change the method's signature.
=> notifier: rename #inc_request to #notify_request

lib/airbrake-ruby/route_sender.rb
Sometimes we have routes that report 0 count. In theory, this should never
happen because if there's a route record, then the count should be at least 1.
I suspect this happens due to a possible race between `send` and
`increment_stats`.
This gets executed: `@routes[route] ||= RouteStat.new`
Then the scheduler switches to `send` and sends the routes. This essentially
sends the route with zero data.
So far I have no better idea and this is kind of a guess rather than a solid
proof.
=> route_sender: fix possible race with increment_stats

lib/airbrake-ruby/route_sender.rb
This reverts commit 71b25575018c4c31e7763eb49326f21f964d28a8.
The fix did not fix anything and it's better to `send` outside mutex so the
thread is not blocked during network operations.
=> Revert "route_sender: fix possible race with increment_stats"

lib/airbrake-ruby/route_sender.rb, spec/route_sender_spec.rb
We change it back to `statusCode` due to internal policies.
=> route_sender: send `status_code` as `statusCode`

lib/airbrake-ruby/filters/git_last_checkout_filter.rb, spec/filters/git_last_checkout_filter_spec.rb
Stops hitting this error on bare ruby usage:
```
NoMethodError: undefined method `to_datetime' for 2018-11-29 16:24:52 -0600:Time
from airbrake-ruby-2.12.0/lib/airbrake-ruby/filters/git_last_checkout_filter.rb:84'
```
The #to_datetime and #rfc3339 methods are both defined in the Date stdlib but are not included by default.
Also the test email regex didn't allow for dashes nor dots which are both relatively common.
=> Fixes missing require for DateTime

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/route_sender.rb, spec/config_spec.rb, spec/notifier_spec.rb
`RouteSender` must respect the `ignore_environments` option because the current
behaviour is inconsistent (e.g. we collect route stats but don't send notices).
The `route_stats` option allows disabling the feature altogether, no matter what
environment is used. When enabled (the default), it will work only in allowed
environments. This should be useful for apps that don't have any routes, which
protects against unwanted `Airbrake.notify_request` calls. Low tier accounts that
don't support the feature should also be configuring this.
=> Add the `route_stats` option and make RouteSender respect envs

README.md
This option is really only for testing and users shouldn't be configuring it. In
order to not confuse anyone, it's better to remove it from the README.
=> README: don't mention 'route_stats_flush_period'

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/notifier.rb, spec/filter_chain_spec.rb
Sometimes users may not be happy with the default behaviour of our
filters (concrete scenario: https://github.com/airbrake/airbrake/issues/883). In
this case we want users to allow deleting a default filter they don't like.
Competes with https://github.com/airbrake/airbrake-ruby/pull/375.
=> Add the ability to delete a filter

lib/airbrake-ruby/route_sender.rb
`RouteStats#send` is actually `RouteSender#send`. No need to hardcode that since
we'd need to update it once more in case we change class/method name.
=> route_sender: don't hardcode class#method in logs

spec/route_sender_spec.rb
There's no need to do it since all the tests pass without it.
=> route_sender_spec: don't sleep

README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/query_sender.rb, lib/airbrake-ruby/route_sender.rb, spec/config_spec.rb, spec/notifier_spec.rb, spec/query_sender_spec.rb, spec/route_sender_spec.rb
`route_stats` was good for routes but since we also collect SQL queries, we need
to adapt. `performance_stats` will configure both of these features. The name
corresponds to the name of the feature in our dashboard.
=> Rename the 'route_stats' option to 'performance_stats'

lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/query_notifier.rb, lib/airbrake-ruby/route_notifier.rb, spec/notifier_spec.rb, spec/query_notifier_spec.rb, spec/route_notifier_spec.rb
In this library "Sender" powers "Notifier". The Notifier has Async and Sync
senders. "Route/QuerySender" resides on the same layer as "Notifier" (and uses
SyncSender internally), therefore it should be named appropriately.
=> Rename Route & Query senders to Route & Query notifiers

lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/route_notifier.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb, spec/route_notifier_spec.rb
RouteNotifier has nothing to do with Notifier. They don't share any code and
don't rely on each other's state. Therefore, we can easily move it to the layer
above.
=> notifier: decouple RouteNotifier

lib/airbrake-ruby.rb, lib/airbrake-ruby/notifier.rb, lib/airbrake-ruby/query_notifier.rb, lib/airbrake-ruby/route_notifier.rb, spec/airbrake_spec.rb, spec/notifier_spec.rb, spec/query_notifier_spec.rb
QueryNotifier has nothing to do with Notifier. They don't share any code and
don't rely on each other's state. Therefore, we can easily move it to the layer
above.
Similar to https://github.com/airbrake/airbrake-ruby/pull/383.
=> notifier: decouple QueryNotifier

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice_notifier.rb, spec/airbrake_spec.rb, spec/notice_notifier_spec.rb, spec/notice_notifier_spec/options_spec.rb
Now that we have all sorts of notifiers in this library, the name `Notifier`
doesn't look too descriptive. It's too generic. It was tempting to rename it to
`ErrorNotifier` but this would likely be confusing. Although we send errors to
Airbrake, the object that we work with is called `Notice`. Had we used `Error`,
`ErrorNotifier` would make more sense, but alas.
Accessing `Airbrake::Notifier` is still possible but each time doing so emits a
warning. Although `Airbrake::Notifier` was marked as private API since its
creation, it's too tempting to use this class in your codebase and I suspect
some people might do that, so I am just being cautions here.
=> Rename Notifier to NoticeNotifier

lib/airbrake-ruby.rb, lib/airbrake-ruby/deploy_notifier.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/query_notifier.rb, lib/airbrake-ruby/route_notifier.rb, spec/airbrake_spec.rb, spec/deploy_notifier_spec.rb, spec/notice_notifier_spec.rb, spec/notice_notifier_spec/options_spec.rb, spec/query_notifier_spec.rb, spec/route_notifier_spec.rb
This change aims to remove duplicative code from notifiers. Every notifier used
to check if the config is valid and raise an error. It makes sense to avoid this
duplication by moving config validation on the layer above, closer to the public
API.
As result, notifiers stopped accepting hashes and expect an instance of Config.
In case people initialize notifiers directly (shouldn't be the case, but who
knows), we show a deprecation warning, that passing a hash is not supported
anymore.
=> airbrake-ruby: validate config in Airbrake#configure

lib/airbrake-ruby.rb, lib/airbrake-ruby/query_notifier.rb, lib/airbrake-ruby/route_notifier.rb, lib/airbrake-ruby/stat.rb, spec/stat_spec.rb
These notifiers share common logic and have exactly the same code. There's an
opportunity to define a general data structure that can be used by any notifier
that accumulates performance statistics.
=> {query,route}_notifier: factor out "stats" to a separate struct

lib/airbrake-ruby/time_truncate.rb, spec/time_truncate_spec.rb
Previously, the time would be converted to UTC without properly adjusting for the given time's time zone.
=> Maintain UTC offset when truncating

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/ignorable.rb, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/performance_notifier.rb, spec/ignorable_spec.rb, spec/notice_spec.rb, spec/performance_notifier_spec.rb
The API:
```ruby
Airbrake.add_performance_filter(&:ignore!)
Airbrake.delete_performance_filter(MyFilter)
```
It behaves *exactly* like `Airbrake.add_filter` and
`Airbrake.delete_filter`. The only difference is that instead of notices
`Airbrake::Request` & `Airbrake::Query` are being yielded.
These objects are called "resources". They don't quack like notices, though,
although they do have `#ignored?` and `#ignore!` methods, which makes them obey
certain rules developed during the `add_filter` rule.
=> Implement the ability to filter requests and queries

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/deploy_notifier.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, spec/airbrake_spec.rb
This new method returns all configured notifiers. This way it's possible to
access performance and deploy notifiers, which is going to be used in the
airbrake gem.
The old `Airbrake#[]` method is a weird citizen now. It can retreive only notice
notifiers. I am not deprecating it yet but in the future it might be removed or
merged with `Airbarke.notifiers`.
=> Implement Airbrake.notifiers

lib/airbrake-ruby/filters/git_repository_filter.rb
Git v2.7 introduced support for `git remote get-url`. Here we are adding a
special case for old git installations (unfortunately, there have been a few bug
reports, so people do run a 5-year old git).
=> git_repository_filter: don't read repo on git 2.6 and lower

lib/airbrake-ruby/filters/git_repository_filter.rb
This way is less noisy. If Airbrake run against a repo that doesn't have a
remote, the following warning is emitted:
% bundle exec rake airbrake:test
fatal: No such remote 'origin'
...
If we read through config, nothing is printed.
=> filters/git_repository: read remote through config

airbrake-ruby.gemspec
I'm seeing an issue with 3.2.0 on jruby, my builds are failing because bundler is attempting to install the ruby version of rbtree3, not the jruby version.
I think the current method of detecting jruby doesn't work in all cases, for example when using rvm on travis.
```
/home/travis/.rvm/gems/jruby-9.1.9.0/extensions/universal-java-1.8/2.3.0/rbtree3-0.5.0/mkmf.log
extconf failed, exit code 1
Gem files will remain installed in
/home/travis/.rvm/gems/jruby-9.1.9.0/gems/rbtree3-0.5.0 for inspection.
Results logged to
/home/travis/.rvm/gems/jruby-9.1.9.0/extensions/universal-java-1.8/2.3.0/rbtree3-0.5.0/gem_make.out
An error occurred while installing rbtree3 (0.5.0), and Bundler cannot
continue.
Make sure that `gem install rbtree3 -v '0.5.0' --source 'https://rubygems.org/'`
succeeds before …
```
=> Improve jruby detection

lib/airbrake-ruby/filters/git_repository_filter.rb, spec/filters/git_repository_filter.rb
Fixes #407 ("Malformed version number string" error with version 3.2.0)
Apparently, if you compile Git from source, it appends some sort of meta
information.
=> git_repository_filter: handle non-standard git versions

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice_notifier.rb
Fixes #406 (Airbrake failing with undefined method `notify_request’ as of 3.2)
This looks ugly but preserves backwards compatibility with current airbrake
gem (v8.0.1).
=> notice_notifier: add 'notify_request' kludge for compatibility

.gitignore, .rubocop.yml, Rakefile, airbrake-ruby.gemspec
The current approach doesn't work with JRuby. The patch that aimed to fix the
issue didn't actually work (duh):
https://github.com/airbrake/airbrake-ruby/pull/408
The problem is that I run `gem build *.gemspec` using CRuby, so the JRuby check
inside the gemspec always has the same outcome. This change builds gems
properly, with `rake gems`.
=> Build this gem on JRuby properly

CHANGELOG.md, lib/airbrake-ruby/filter_chain.rb, spec/filter_chain_spec.rb
Invoking `#inspect` on JRuby produces:
```
TypeError: no implicit conversion of Array into String
```
https://circleci.com/gh/airbrake/airbrake/3429
=> filter_chain: fix bugged #inspect when a chain has no filters

CHANGELOG.md, lib/airbrake-ruby/filters/git_repository_filter.rb, spec/filters/git_repository_filter.rb
Fixes ``undefined method `split' for nil:NilClass`` when Git is not
installed (could easily happen inside a Docker container).
=> filters/git_repository: don't filter when Git is not installed

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/performance_notifier.rb, spec/performance_notifier_spec.rb
Adds support for `func`, `file` & `line` for `Airbrake.notify_query`.
```rb
Airbrake.notify_query(
method: 'POST',
route: '/foo',
query: 'SELECT * FROM things',
func: 'foo',
file: 'foo.rb',
line: 123,
start_time: Time.new(2018, 1, 1, 0, 49, 0, 0),
end_time: Time.new(2018, 1, 1, 0, 50, 0, 0)
)
```
=> performance_notifier: add the ability to attach caller locations

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/request.rb, spec/performance_notifier_spec.rb
`Airbrake.notify_{request,query}` can now send environment information.
Additionally, when `Query` or `Request` are serialised to Hash, we don't include
`nil` values, so we rely on the backend default values.
=> query,request: add support for environment

lib/airbrake-ruby/notice_notifier.rb
This is already defined in the Airbrake module. No need to duplicate.
=> notice_notifier: delete the LOG_LABEL constant

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/deploy_notifier.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, spec/config_spec.rb
I've planned to keep this for a longer time, however fast pace with APM features requires a major version bump. This is a preparation for the major breaking change: making the Config object a singleton. The reasons for that will be described in the future, but for now we're just deleting stuff that shouldn't survive a major bump.
=> Remove deprecated functionality

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
This change is consistent with the rest of the notify methods:
* notify_query
* notify_request
=> airbrake-ruby: deprecate #create_deploy in favour of #notify_deploy

lib/airbrake-ruby.rb, lib/airbrake-ruby/notice_notifier.rb, spec/airbrake_spec.rb
This feature starts getting in the way of future development of the library:
* We have to maintain a complex API to support different configurations for many
notifiers (we have 3 now vs 1 when we were releasing this functionality). We
want a simple API
* It's hard to pass the config object around. If a component that sits at the
bottom layer of the library architecture suddenly needs to read some config
value, we have to pass it through all the layers, from the top to the
bottom. This was a compromise since the very beginning but back then it was
easy to maintain it (although it always bugged me). We now rapidly add new
features and this approach does not scale well - too much clutter
* Classes know more than they really need. As a result, testing becomes harder
since we need to inject …
=> Remove the ability to configure multiple notifiers

CHANGELOG.md, lib/airbrake-ruby.rb
This goes in line with `Airbrake.configure(:name)` deprecation.
=> airbrake-ruby: deprecate Airbrake#[]

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
This method is not needed now since `Airbrake[:default]` == `Airbrake`.
=> airbrake-ruby: delete deprecated Airbrake#[]

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
This method is no longer needed because we no longer allow configuring multiple
notifiers.
I also deleted some tests: they are duplicative and we already test that
functionality in notifiers. The wrapper is trivial enough, it doesn't introduce
anything new.
=> airbrake-ruby: delete deprecated Airbrake#notifiers

lib/airbrake-ruby.rb, lib/airbrake-ruby/async_sender.rb, lib/airbrake-ruby/backtrace.rb, lib/airbrake-ruby/code_hunk.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/filters/exception_attributes_filter.rb, lib/airbrake-ruby/filters/git_last_checkout_filter.rb, lib/airbrake-ruby/filters/keys_blacklist.rb, lib/airbrake-ruby/filters/keys_filter.rb, lib/airbrake-ruby/filters/keys_whitelist.rb, lib/airbrake-ruby/loggable.rb, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/response.rb, lib/airbrake-ruby/sync_sender.rb, spec/async_sender_spec.rb, spec/backtrace_spec.rb, spec/code_hunk_spec.rb, spec/filters/exception_attributes_filter_spec.rb, spec/filters/git_last_checkout_filter_spec.rb, spec/filters/keys_blacklist_spec.rb, spec/filters/keys_whitelist_spec.rb, spec/response_spec.rb, spec/sync_sender_spec.rb
Since the Airbrake module holds only one instance of every notifier, it opens
the gate to centralised logging. We no longer need to toss logger instances
around and inject them into every class that needs logging.
It always bothered me that we were doing it but it was the only way to go if we
wanted to maintain a fat wrapper that the Airbrake module was. Loggable is super
easy to use and I was able to `include` and it "just worked". Moreover, testing
is a ton easier now.
=> Factor out Logger to the Loggable module

lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/request.rb, spec/performance_notifier_spec.rb
There was a change in the backend: instead of sending environment information
with every request/query, we send it at the top level of the JSON payload.
This is a breaking change but the airbrake gem hasn't been updated yet to work
with environments, so it's not a huge deal.
=> performance_notifier: attach 'environment' to the top level of JSON

CHANGELOG.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/loggable.rb
There's a bug in v4.0.0, which prevents using `Airbrake.configure`. This is
because we instantiate in a weird way: the objects we instantiate don't have any
implementation *yet* and they contain no methods.
If we instantiate after the class has methods, everything will operate normally.
=> Fixed incorrect "instance" definition

lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/validator.rb, spec/config/validator_spec.rb, spec/config_spec.rb
We can easily return promises from the Validator. The old API was not very
well done (looking at you, `@config.validation_error_message`). With help of
promises (aka Result object) we are able to pass result (ok or not ok) and error
message at the same time.
This new Validator is a static class. The old Validator didn't carry any state
and it didn't look clean to me when we instantiated it.
The new Validator acquired a new method: `#check_notify_ability`. This change
will help in cleaning Notifier classes, which have repetitive guards.
I also cleaned up tests, to make them less repetitive.
=> Rewrite Config::Validator to support promises

airbrake-ruby.gemspec, spec/config_spec.rb, spec/spec_helper.rb
This is achieved with `rspec-its`.
=> spec/config: cleanup specs to be more terse and readable

lib/airbrake-ruby/config.rb, lib/airbrake-ruby/promise.rb, spec/config/validator_spec.rb, spec/config_spec.rb, spec/promise_spec.rb
We shouldn't be littering with `value == :ok` checks. `#rejected?` & `#resolved?` improve readability.
=> Improve Promise with #rejected? & #resolved?

lib/airbrake-ruby/config.rb, lib/airbrake-ruby/deploy_notifier.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, spec/config_spec.rb, spec/deploy_notifier_spec.rb, spec/notice_notifier_spec.rb, spec/notice_notifier_spec/options_spec.rb, spec/performance_notifier_spec.rb
We want to be able to add_filter's to Airbrake even when it's not
"configured". This resolves the headache with load order in the Rails
integration: add whenever you can but notify only when configured.
It also resolves the problem with notify methods that return nil. Users of
our API had to perform annoying nil checking, now they don't need this and can
fully rely on promises.
=> Implement and use Config#check_configuration in notifiers

CHANGELOG.md, lib/airbrake-ruby.rb, spec/deploy_notifier_spec.rb, spec/notice_notifier_spec.rb, spec/performance_notifier_spec.rb
When a notifier is not configured, we can `add_filter` but `notify` won't have
effect. This accompanies https://github.com/airbrake/airbrake-ruby/pull/445.
=> Delete NilNotifiers and rely on notifier config checks

lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/request.rb
Currently, we require that endpoint destination should match the resource
name. This is rather convenient since we can rely on convention, however if the
backend doesn't follow it, our code breaks (if we add new models).
With this change we use the cargo->destination metaphor and add it to our
models, so every model declares what it carries and where it should be
sent. PerformanceNotifier doesn't make any assumptions anymore.
=> performance_notifier: make resource name independent

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/request.rb, lib/airbrake-ruby/stat.rb, spec/performance_notifier_spec.rb, spec/stat_spec.rb
`Airbrake.notify_performance_breakdown` increments performance breakdown
statistics of a certain route.
Performance breakdown consists of groups such as `db`, `view`, `http`, etc. (up
to 10). Names are arbitrary.
=> Add the ability to send performance breakdown

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes https://github.com/airbrake/airbrake/issues/931.
(`Airbrake::Error: :project_id is required` is thrown for ignored environment)
This is technically not a bug since we even test that we raise an error, but an
oversight.
=> airbrake-ruby: don't raise error when there's no project id/key

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes #460 (blacklist_keys config doesn't work)
The problem was that we never reconfigured already instantiated notifiers. We
always spawn notifiers as soon as the library is required but they get spawned
without some of default filters that are supposed to work given certain options
such as `blacklist_keys`.
The new `#reset` method respawns all notifiers on `#configure`. We have to
respawn so the new notifiers pickup the config. We need to spawn without the
user config so all the methods are working (e.g. notify returns a rejected
promise and such).
=> airbrake-ruby: make sure optional filters are loaded

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
The `reset` method introduced in v4.2.2 was resetting Airbrake every time we
call `configure`. This can result in default filters being lost. E.g. we
`add_filter` and then `configure`.
There are two solutions:
* we add filters within `configure`
* we don't call reset when notifiers are already registered
I chose the latter because it's a simpler approach and it does the job. I will
keep in mind the first approach since it sounds more logical to me. Currently,
we decouple "configuration" and filters, however they are the same thing and
adding filters *is* configuration. That said, this approach has caveats. For
example, I wan't to add some filters in some integration. I don't want to
reconfigure the whole thing, I just want to append my tiny little filter.
=> airbrake-ruby: don't overwrite notifiers on #configure

spec/filters/git_revision_filter_spec.rb
This failure can be reproduced with:
```
bundle exec rspec --seed 59264
expected: ("root/dir/.git/HEAD")
got: ("/home/kyrylo/code/airbrake/ruby/spec/spec_helper.rb")
```
The problem is that `let` lazily instantiates `Airbrake::Notice`, which calls
`File.exist?` in CodeHunk with unexpected arguments.
=> filters/git_revision: fix sporadic failure

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice_notifier.rb, spec/airbrake_spec.rb, spec/notice_notifier_spec.rb, spec/notice_notifier_spec/options_spec.rb
Fixes #468 (blacklist_keys not being filtered out in version 4.2.3)
The problem was that at the time when we initialize NoticeNotifier (on library
load) the Config has no blacklist/whitelist keys specified. Therefore, when we
`configure` Airbrake, newly set values have no effect.
With this change we move conditional filter initialization out of
NoticeNotifier. The risk is that calling `configure` twice will append the same
conditional filters twice. Therefore, `reset` must be called prior to second
`configure` (but it's probably a good idea not to call it twice and it should be
very uncommon).
=> airbrake-ruby: initialize notice notifier with filters

lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes #471 (airbrake:deploy issue with airbrake-ruby (4.2.4))
=> airbrake-ruby: fix notifier accessors returning wrong notifiers

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/benchmark.rb, lib/airbrake-ruby/timed_trace.rb, spec/benchmark_spec.rb, spec/timed_trace_spec.rb
TimedTrace represents a chunk of code performance of which was measured and
stored under a label. The chunk is called a "span".
```ruby
timed_trace = TimedTrace.new
timed_trace.span('http request') do
http.get('example.com')
end
timed_trace.spans #=> { 'http request' => 0.123 }
```
=> Add TimedTrace

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/request.rb, lib/airbrake-ruby/stashable.rb, spec/airbrake_spec.rb, spec/notice_spec.rb, spec/performance_breakdown_spec.rb, spec/query_spec.rb, spec/request_spec.rb, spec/stashable_spec.rb
This stash can be accessed from performance filters.
```ruby
query_info = { query: '...', ...}
stash = { request_id: 123 }
Airbrake.notify_query(query_info, stash)
```
```rb
Airbrake.add_performance_filter do |resource|
do_something if resource.stash[:request_id] == 123
end
```
=> Added the ability to send stash for resources

CHANGELOG.md, lib/airbrake-ruby/async_sender.rb, spec/async_sender_spec.rb
Fixes #483 ("NoMethodError: undefined method `then' for nil:NilClass" when
sending first notice with a promise)
=> async_sender: return a rejected promise when capacity is maxed out

CHANGELOG.md, lib/airbrake-ruby/performance_notifier.rb
In #488 a lot of users mentioned that they see performance slowdown when they
enable APM. My theory is that this is due to the fact that we log debug
output. Converting `payload` to string is expensive. The Logger library offers
another way to log:
https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html#class-Logger-label-How+to+log+a+message
> The block form allows you to create potentially complex log messages, but to
> delay their evaluation until and unless the message is logged.
This should help with performance. I dropped a `binding.pry` in the context of
the debug statement and ran benchmarks to verify this (logger level is
`Logger::ERROR`):
```
[7] pry(#<Airbrake::PerformanceNotifier>)> ::Benchmark.ips do |ips|
[7] pry(#<Airbrake::PerformanceNotifier>)* …
```
=> performance_notifier: delay string conversion of payload on logging

CHANGELOG.md, lib/airbrake-ruby/stat.rb, spec/stat_spec.rb
Hopefully fixes #488 (Increase in CPU usage when performance_stats = true)
I noticed that dumping TDigest is very slow. Here's performance payload with
TDigests:
```
Warming up --------------------------------------
1.553k i/100ms
Calculating -------------------------------------
15.906k (± 3.0%) i/s -     80.756k in   5.082704s
```
And here's the same payload but without TDigests.
```
Warming up --------------------------------------
4.443k i/100ms
Calculating -------------------------------------
45.498k (± 1.8%) i/s -    231.036k in   5.079495s
```
It makes sense to not dump TDigests because it's mostly clutter and it makes
performance much worse.
=> stat: define custom #inspect

README.md
The [Airbrake Performance Monitoring](https://airbrake.io/product/performance) feature is no longer in beta and is available to all accounts. This updates the readme to reflect this.
=> Update readme to reflect live Performance Monitoring

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/performance_notifier.rb, spec/config_spec.rb, spec/performance_notifier_spec.rb
Likely fixes:
* airbrake/airbrake#994 (Memory usage)
* airbrake/airbrake#990 (CPU and Average Response
increased after version 7)
The SQL query collection feature is still in alpha and we display it only for
certain accounts. Therefore, the vast majority of our customers cannot even see
what airbrake-ruby collects. Since the feature is still in alpha, it is
currently buggy (in a sense that it consumes too much memory & CPU power).
I profiled a Rails app on a certain route with `memory_profiler` for Rack Mini
Profiler and I can see a significant increase of memory usage.
=== performance_stats = false
```
Total allocated: 12434583 bytes (145711 objects)
Total retained:  508023 bytes (3346 objects)
allocated memory by gem
264  airbrake/lib
```
=== performance_stats = true && query_stats = …
=> Implement the "query_stats" option and disable it

lib/airbrake-ruby/performance_notifier.rb
In the current version of the code the background thread clears the variable
that the parent thread reserved for it. This is illogical and probably error
prone.
With this change the parent thread takes care of cleaning up the child, so that
the child knows nothing of how it is managed. This makes much more sense.
=> performance_notifier: always join the background thread

lib/airbrake-ruby.rb, lib/airbrake-ruby/performance_notifier.rb, spec/filters/thread_filter_spec.rb, spec/performance_notifier_spec.rb
Previously, we would spawn a new thread every 15 seconds. According to
RackMiniProfile, this would use around 1.05MB of memory per request on my route
that makes a few SQL queries, which makes it #1 gem that wastes memory for my
Rails 5 app (both allocated and retained).
Spawning threads implies significant overhead, so I realised we don't actually
need to spawn anything. We can have just one thread that sleeps until more work
is given. Then this timer thread would fire and sleep again (unless there's more
work to do).
As result, we use a lot less memory (basically, only the memory needed to
pass payload to the worker thread). The downside is that we no longer support
promises properly (if a request fails in background, the promise will not tell),
but this seems to be a reasonable …
=> performance_notifier: reuse the same thread for flushing

CHANGELOG.md, lib/airbrake-ruby/filters/sql_filter.rb, spec/filters/sql_filter_spec.rb
The number of arguments to `VALUES` or `IN` shouldn't matter. With this change
our grouping is more consistent.
=> filters/sql: apply more aggressive grouping

CHANGELOG.md, lib/airbrake-ruby/filters/sql_filter.rb, spec/filters/sql_filter_spec.rb
Some queries are just noise. We want to be able to show only relevant and
valuable information, thus it makes sense to ignore the noise.
=> filters/sql: ignore certain queries

README.md
=> Fix typo in query stats section

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/performance_notifier.rb, spec/airbrake_spec.rb, spec/performance_notifier_spec.rb
`PerformanceNotifier#notify_sync` exists for the same reasons as
`NoticeNotifier#notify_sync`.
In certain scenarios, such as Resque jobs, `AsyncSender` dies before it can send
something. Because `PerformanceNotifier` waits 15 seconds before sending
payload, it's guaranteed that once a Resque job finishes, it also kills
`PerformanceNotifier` before it can send. This is the unfortunate effect of
forking.
To cope with this, we must send synchronously.
=> performance_notifier: add #notify_sync

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes #517 (On shutdown creates performance_notifier only to close it)
=> airbrake-ruby: don't spawn notifiers on #close calls

CHANGELOG.md, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/queue.rb, lib/airbrake-ruby/request.rb, spec/performance_breakdown_spec.rb, spec/query_spec.rb, spec/queue_spec.rb, spec/request_spec.rb
In `PerformanceNotifier` there's a possible situtation when `start_time` and
`end_time` are the same. If that's the case, the backend will reject the
resource because `Airbrake::Stat` would report zero `sum`. As result, the
backend will reject what we send:
```
**Airbrake: sum <= 0
```
=> Fix default `end_time` sometimes being equal to `start_time`

CHANGELOG.md, lib/airbrake-ruby/notice_notifier.rb, spec/notice_notifier_spec.rb
Addresses #524 (Error Airbrake: performance notifier closed causes deadlock)
A user reported that he saw the following message in the logs:
> Airbrake::Error (attempted to build deadlock; recursive locking with closed
Airbrake instance)
Because exceptions are stringified, the error message can get very confusing. In
issue #524 the user thought that there's a deadlock in airbrake-ruby (me too,
to be honest), but when I took a closer look, it turned out that we print the
exception we're building as a string.
I changed the message, so it's more obvious what's going on.
=> notice_notifier: fix confusing error message

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/benchmark.rb, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/queue.rb, lib/airbrake-ruby/request.rb, spec/performance_notifier_spec.rb
There are a few reasons for this change:
1. We use realtime to measure performance for the `:total` stat. This is no
good, especially since we use monotonic time for other groups. It is
inconsitent and confusing
2. New functionality requires a better API. Specifically, we want to be able to
send timing of a certain job. To achieve that we wrap the job in a benchmark
`measure` call. The problem is that our API doesn't make it easy to send
already calculated timing. `start_time` makes the user code very clunky and
confusing
Before:
```
start_time = Time.now
calculate_operation
Airbrake.notify_request(
...,
start_time: start_time,
end_time: Time.now,
)
```
After:
```
timing = Airbrake::Benchmark.measure do
calculate_operation
end
Airbrake.notify_request(
...,
timing: timing,
)
```
=> Deprecate :{start,end}_time, add :timing instead

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb, spec/performance_notifier_spec.rb
It works exactly the same as `query_stats`. Users who don't need the feature can
disable it.
=> Add `job_stats` to the config

CHANGELOG.md, lib/airbrake-ruby/queue.rb, spec/queue_spec.rb
Alternative solution to the problem described in:
https://github.com/airbrake/airbrake-ruby/pull/537
We've added `Airbrake::Queue` but forgot to define `#route`. Hence, some filters
that call `resource.route` will raise `NoMethodError`
=> queue: add #route for API compatibility

Gemfile, airbrake-ruby.gemspec, lib/airbrake-ruby.rb, lib/airbrake-ruby/filters/thread_filter.rb, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/queue.rb, lib/airbrake-ruby/request.rb, lib/airbrake-ruby/stat.rb, lib/airbrake-ruby/truncator.rb, spec/filters/thread_filter_spec.rb
- Allow rake 13.x on Ruby 2.2+.
- The whole safe_level feature is a deprecated noop in 2.7+.
- Fixed all keyword parameter warnings.
- KeywordStruct wrapper to allow Struct with keyword parameters on
Ruby 2.7, or faking the behavior on other Ruby versions/platforms.
=> Fix all Ruby 2.7 warnings

.gitignore
Make local development easier for rvm and rbenv users.
=> Ignore .ruby-version and .ruby-gemset

lib/airbrake-ruby/performance_notifier.rb
Since we are sending JSON, it makes sense to log JSON, instead of Ruby objects.
Before:
```
DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send:
{#<Airbrake::Queue:0x00007fedb7e748f0 @time_utc="2020-02-07T05:27:00+00:00",
@queue="BadWorker", @error_count=0, @groups={},
@start_time=2020-02-07 13:27:40 +0800, @end_time=2020-02-07 13:27:41 +0800,
@timing=8, @time=2020-02-07 13:27:40 +0800, @stash={}
>=>{:total=>#<struct Airbrake::Stat count=100, sum=5390.0, sumsq=378058.0>}}
```
After:
```
DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send:
{"queues"=>[{"queue"=>"BadWorker", "errorCount"=>0,
"time"=>"2020-02-07T05:28:00+00:00",
"count"=>100, "sum"=>5318.0, "sumsq"=>359568.0,
"tdigest"=>"AAAAA......."}]}
```
=> performance_notifier: log JSON instead of Ruby objects

lib/airbrake-ruby/tdigest.rb
Since this code was vendored from another project, it did not adhere the Ruby style we use in this one. This wasn't an issue until I started reading it, since it may be the cause of a bug. With these minor refactorings the code is a little bit better and easier to read.
=> Refactor TDigest to use more idiomatic Ruby

lib/airbrake-ruby/tdigest.rb
In a similar fashion to https://github.com/airbrake/airbrake-ruby/pull/547 we simplify TDigest and make it more idiomatic. These changes make the code a tiny bit clearer.
=> Simplify TDigest class

CHANGELOG.md, lib/airbrake-ruby/stat.rb, spec/stat_spec.rb
Once in a while our backend would reject a perfectly valid payload with the
following message (the actual numbers can vary):
```
ERROR -- : **Airbrake: tdigest.count=98, but count=100
```
In `Airbrake::Stat` we dump 2 counts: one comes from the Stat class itself, the
other one is provided by the TDigest implementation. The Stat count would always
be stable (100 calls means the count is 100). The TDigest count sometimes would
be less (98 in this particular example).
Java implementation of TDigest defines `size()` as:
> the number of points that have been added to this TDigest
I don't have a good grasp with the tdigest algorithm but during hours of
experimentation I established that the TDigest count is dependent on the values
we feed to the tdigest. This could mean two things:
1. The Ruby …
=> stat: delete 'count' method and use tdigest.size as 'count'

CHANGELOG.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/loggable.rb, spec/config_spec.rb, spec/loggable_spec.rb
Issue #550 mentions that README states that our default logger is `Logger::WARN`,
however the code never sets that level. The default value is `Logger::DEBUG`,
which is unwanted, since it generates a lot of clutter.
=> {config,loggable}: set default Logger level to Logger::WARN

lib/airbrake-ruby/performance_notifier.rb
When raising:
* there's no point in printing "signature" because Ruby will
provide a file and line number
* there's no need to print `payload` because we already state in words that it's
empty (so we would always print `({})`)
=> performance_notifier: strip useless info from the raise message

CHANGELOG.md, lib/airbrake-ruby/monotonic_time.rb, lib/airbrake-ruby/performance_notifier.rb, spec/monotonic_time_spec.rb
Fixes (hopefully) #553 (ThreadError: deadlock; recursive locking in
Airbrake::PerformanceNotifier)
While I've never been able to reproduce the mentioned bug personally, I believe
the problem is the faulty timer mechanism. We mess with background threads and
shared state, which is always prone to bugs.
In this new version of the code we use monitors and condition variables. It
allows us a better synchronisation for `@payload` access. We got rid of the
unwanted `@waiting` variable and stopped calling hacky `Thread.pass`. Basically,
we let Ruby do its threading thing and we don't interrupt manually.
The new implementation became simpler and more stable and I do hope I got this
right.
=> performance_notifier: refactor timer algorithm to use condition vars

.rubocop.yml, lib/airbrake-ruby.rb, lib/airbrake-ruby/notice.rb, lib/airbrake-ruby/notice_notifier.rb
I bumped Rubocop in https://github.com/airbrake/airbrake-ruby/pull/556 and saw a bunch of new offences. However, https://github.com/airbrake/airbrake-ruby/pull/556 will not be merged due to old Ruby support.
So what I am doing is cherry-picking a few useful changes from https://github.com/airbrake/airbrake-ruby/pull/556 and merging them with `master`.
=> Resolve future Rubocop offences

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb
In the Airbrake gem we have filters that add the following keys to the context
payload:
* referer
* httpMethod
* userAddr
* userAgent
This information is not critical for our services to work and sometimes users
need to filter that due to various reasons. Specifically, someone requested to
be able to filter `userAddr` due to GDPR reasons.
=> filters/keys: add referer, httpMethod, userAddr & userAgent

CHANGELOG.md, lib/airbrake-ruby.rb, spec/airbrake_spec.rb
Fixes #561 (Multiple `Airbrake.configure` calls append the same filters to the
filter chain)
This solution makes sure we don't reappend the same "static" filters over and
over when we call `Airbrake.configure`. Static here means that the filters
implement exactly the same algorithm, so they are duplicative and thus not
necessary.
There are non-static filters. For example, if users configure blacklist keys
twice, the same filter will be added. The filter chain will have two instances
of `KeysBlacklistFilter`. However this is okay because both of them will filter
different keys (therefore the algorithm is different).
=> airbrake-ruby: do not reappend same filters

CHANGELOG.md, lib/airbrake-ruby/stat.rb
Possibly fixes #545
(>4.4.0 <=4.13.0 causing RuntimeError: can't add a new key into hash during
iteration)
=> stat: synchronize `to_h` with `increment_ms`

CHANGELOG.md, lib/airbrake-ruby/filters/git_last_checkout_filter.rb, spec/filters/git_last_checkout_filter_spec.rb
In certain environments, when a deploy starts, end deploy user might not be the
one who started the deploy. For example, if you deploy via Ansible, the script
could create a fake user who would pull the web app repo and deploy it for
you. Even though you started the script, the filter will pick up the fake user
name, since `.git` was created by that user.
To work around that, we introduce the `AIRBRAKE_DEPLOY_USERNAME` env
variable. With help of it we can forward the username from Ansible to Ruby.
=> filters/git_last_checkout: add support for AIRBRAKE_DEPLOY_USERNAME

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/filter_chain.rb, lib/airbrake-ruby/notice_notifier.rb, spec/airbrake_spec.rb, spec/filter_chain_spec.rb
In e4db77de1ea6203dbcec6c68234d6ce7ffd7139a, in attempt to fix appending same
filters over and over I actually introduced a bug. Some filters wouldn't be
appended at all.
In order to solve that, I have to add special API that allows me to append
filters conditionally. Now the code that calls `add_filter` can decide whether
it wants to append a filter or skip. We achieve it with
`NoticeNotifier#has_filter?`.
=> Fix some default filters not being appended

airbrake-ruby.gemspec, spec/performance_notifier_spec.rb
This update fixes the following warning, which can be seen when we run the test
suite:
```
webmock-2.3.2/lib/webmock/util/json.rb:27:
warning: assigned but unused variable - pos
```
=> Bump webmock to `~> 3.8`

CHANGELOG.md, lib/airbrake-ruby/thread_pool.rb, spec/thread_pool_spec.rb
Fixes #576 (ThreadError: can't move to the enclosed thread group)
When we `Airbrake.notify` inside a `fork` block, `ThreadPool` tries to respawn
workers (which were killed by the `fork`) to the same `ThreadGroup`, which was
created in the parent thread. The problem is that that `ThreadGroup` is already
finalised in that parent thread and no new threads can be added anymore.  The
fix is to create a new `ThreadGroup` on `fork`. This way every process will have
its own `ThreadGroup`.
=> thread_pool: create a new thread group per process

CHANGELOG.md, README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/filters/keys_allowlist.rb, lib/airbrake-ruby/filters/keys_blocklist.rb, lib/airbrake-ruby/filters/keys_filter.rb, spec/airbrake_spec.rb, spec/config_spec.rb, spec/filters/keys_allowlist_spec.rb, spec/filters/keys_blocklist_spec.rb, spec/filters/sql_filter_spec.rb, spec/notice_notifier/options_spec.rb
Replaces #579.
Background:
* The technology industry has began moving away from terms such as master/slave
and white list /blacklist.
* A recent tweet about this
https://twitter.com/leahculver/status/1269109776983547904
=> Rename "blacklist" to "blocklist" and "whitelist" to "allowlist"

spec/airbrake_spec.rb
In this file we mix `described_class` and `Airbrake`. Let's just use one
standard form: `described_class`. No functional changes.
=> spec/airbrake: replace "Airbrake" with "described_class"

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/validator.rb, spec/config/validator_spec.rb, spec/config_spec.rb
Configures Airbrake error reporting. By default, it's enabled (recommended).
=> config: add the 'error_notifications' option

spec/airbrake_spec.rb
We are testing class methods, so the title was incorrect.
=> spec/airbrake: change '#' to '.'

lib/airbrake-ruby.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/remote_settings.rb, lib/airbrake-ruby/remote_settings/settings_data.rb, spec/airbrake_spec.rb, spec/config_spec.rb, spec/remote_settings/settings_data_spec.rb, spec/remote_settings_spec.rb
A remote config is a WIP feature which will allow you to configure your notifier
from your project settings.
=> Implement support for the remote config

lib/airbrake-ruby.rb
Although we explicitly say we return `void`, the type of the return value
changes from time to time (as we introduce new modifications to the method).
In order to be consistent, let's just return `nil` all the time.
=> airbrake-ruby: always return `nil` on `#close`

lib/airbrake-ruby.rb, lib/airbrake-ruby/async_sender.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/remote_settings/settings_data.rb, lib/airbrake-ruby/sync_sender.rb, spec/config_spec.rb, spec/remote_settings/settings_data_spec.rb
We need to be able to use different API hosts when sending APM and Error
data. This will be useful for us when we introduce remote configuration.
=> remote_settings/settings_data: add support for host configuration

lib/airbrake-ruby.rb, lib/airbrake-ruby/config/processor.rb, spec/airbrake_spec.rb, spec/config/processor_spec.rb
Rubocop is going crazy about the complexity of `process_config_options`. It's
high time to refactor it! Adding a helper class helps to achieve better
testability and lessen the complexity. Rubocop is happy now (and probably your
brain, too).
=> airbrake: factor out complex configuration logic to Processor

CHANGELOG.md, lib/airbrake-ruby/remote_settings/settings_data.rb, spec/remote_settings/settings_data_spec.rb, spec/remote_settings_spec.rb
The old bucket is gone, so we need to update the code to use a new name.
=> remote_settings/settings_data: update S3 bucket name

CHANGELOG.md, lib/airbrake-ruby/filters/keys_filter.rb, spec/filters/keys_blocklist_spec.rb, spec/notice_spec.rb
Fixes #592 (Session deep values are modified if it contains filtered (blocklist)
keys)
=> filters/keys: duplicate hashes while filtering

CHANGELOG.md, benchmarks/performance.rb, lib/airbrake-ruby/performance_breakdown.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/query.rb, lib/airbrake-ruby/queue.rb, lib/airbrake-ruby/request.rb, lib/airbrake-ruby/stat.rb, spec/performance_breakdown_spec.rb, spec/performance_notifier_spec.rb, spec/query_spec.rb, spec/queue_spec.rb, spec/request_spec.rb, spec/stat_spec.rb
=> performance_notifier: drop support for :{start,end}_time params

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
=> config: drop support for `blacklist_keys` & `whitelist_keys`

CHANGELOG.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/processor.rb, lib/airbrake-ruby/remote_settings.rb, lib/airbrake-ruby/remote_settings/settings_data.rb, spec/config_spec.rb, spec/remote_settings/settings_data_spec.rb, spec/remote_settings_spec.rb
At the moment there's a bug with remote configuration. A user would install the
new notifier but the notifier would use our staging S3 bucket to fetch
configs. Instead, we should hardcode the bucket path to production because
that's the goal. A helper option called `remote_config_host` was added. With
help of it can easily test the functionality.
=> Make it possible to configure remote config host

lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/processor.rb, spec/config/processor_spec.rb, spec/config_spec.rb
This temporary option was needed for testing the feature, now we can get rid of
it and use the feature by default.
=> config: delete __remote_configuration

CHANGELOG.md, lib/airbrake-ruby/remote_settings/settings_data.rb, spec/remote_settings/settings_data_spec.rb
If `config_route` is `''`, then it will be used as the host for the remote
config. This is a bug, empty strings should be ignored and the default host
should be used.
=> remote_settings: ignore empty string in 'config_route'

CHANGELOG.md, lib/airbrake-ruby/remote_settings/settings_data.rb, spec/remote_settings/settings_data_spec.rb, spec/remote_settings_spec.rb
Normally `config_route` is specified as `2020-01-01/config/...`. However due to
a bug the returned value from the `#config_route` method will be wrong. Instead
of returning the provided host + config_path we return just `config_path`.
=> remote_settings: fix bug in #config_route

spec/filters/git_last_checkout_filter_spec.rb
This test will not pass if your email includes a subdomain. The new regexp
enables subdomain support.
```
[5] pry(main)> "a@a.b.com".match(/\A\w+[\w.-]*@(\w+\.)+\w+\z/)
=> #<MatchData "a@a.b.com" 1:"b.">
[7] pry(main)> "a@foo.com".match(/\A\w+[\w.-]*@(\w+\.)+\w+\z/)
=> #<MatchData "a@foo.com" 1:"foo.">
```
Thanks to: @derSascha
=> filters/git_last_checkout_spec: support subdomains in e-mail regex

CHANGELOG.md, lib/airbrake-ruby/remote_settings.rb, spec/remote_settings_spec.rb
Some of our users complain that our airbrake-ruby notifier tries to dump the
remote config that we pull from S3 to the gem directory. The OS user that is
running the code may not have write access to that directory and therefore
writing the remote config will fail.
There's no good universal location to keep persistent remote config, so it's
easier just to delete the config.
=> remote_settings: delete the code for config dumping/loading

CHANGELOG.md, lib/airbrake-ruby/config/processor.rb, spec/config/processor_spec.rb
People who depend on this library shouldn't be concerned with stubbing notifier
config HTTP GET calls in their test suites. By tying this with 'environment' we
win a lot: no need to document anything and no need to do anything for those who
depend on airbrake-ruby.
=> config/processor: disable notifier config polling for test envs

CHANGELOG.md, lib/airbrake-ruby/remote_settings.rb, spec/remote_settings_spec.rb
Everything that is not 200 should be treated as error.
=> remote_settings: rely on status codes for detecting errors

lib/airbrake-ruby/config/processor.rb, spec/config/processor_spec.rb
This PR allow to developers to disable the remote config feature if set `remote_config_host` to `nil` in Airbrake configuration. Related with: #626
=> Disable remote config if remote_config_host is nil

CHANGELOG.md, README.md, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/config/processor.rb, spec/config/processor_spec.rb, spec/config_spec.rb
Instead of setting `remote_config_host` to `nil`, which looks like a hack, users
are supposed to configure the `remote_config` option.
=> Add `remote_config` and use it instead of `remote_config_host: nil` to disable notifier config polling

lib/airbrake-ruby/filters/thread_filter.rb, spec/filters/thread_filter_spec.rb
We no longer support Ruby 2.2 and lower, so `#name` is always available to us.
=> filters/thread: delete Thread#name check

spec/tdigest_spec.rb
Example failure:
https://app.circleci.com/pipelines/github/airbrake/airbrake-ruby/194/workflows/e15ff445-0bc3-4ff7-9499-0c4a91ddd068/jobs/9292/parallel-runs/0/steps/0-103?invite=true
This can happen only on JRuby.
=> spec/tdigest: fix sporadically failing test on JRuby

CHANGELOG.md, lib/airbrake-ruby/async_sender.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/thread_pool.rb, spec/performance_notifier_spec.rb, spec/thread_pool_spec.rb
Instead of printing `thread pool closed` twice (for perf notifier and for notice
notifier), we print two separate log messages, so that it looks less confusing
why the same message was printed twice.
=> async_sender: improve logging when closing thread pools

README.md
related to discussion in
* https://github.com/airbrake/airbrake-ruby/pull/649
* https://github.com/airbrake/airbrake-ruby/pull/648
@kyrylo 
In the end I've decided just to submit this one example as the example with ENV variables is ugly once limited to 80 chars per line (and will just confuse everyone)
=> add_filter example to README

airbrake-ruby.gemspec
The build works without it now.
=> gemspec: don't lock public_suffix anymore

CHANGELOG.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/context.rb, lib/airbrake-ruby/filters/context_filter.rb, lib/airbrake-ruby/notice_notifier.rb, spec/context_spec.rb, spec/filters/context_filter_spec.rb
Fixes #658 (Is Airbrake.merge_context thread safe?)
This makes sure any operations on the context hash are thread-safe. We do
synchronize calls around the code that attaches the context object to the error
report but the context object is not thread-safe itself.
=> Implement  a thread-safe `Airbrake::Context`

.rubocop.yml, CHANGELOG.md, lib/airbrake-ruby/filters/git_last_checkout_filter.rb, lib/airbrake-ruby/thread_pool.rb, spec/filters/git_revision_filter_spec.rb, spec/thread_pool_spec.rb
Some of our users complained that `message.inspect` "pressures" their server
memory. Indeed, the dumped string can be large (up to 64KB).
Instead, let's change the severity of this message to `info`, so that it won't
be printed by default. It's not really an error anyway, and the `info` severity
suits it perfectly.
`message.inspect` also won't be called by default anymore, since it's wrapped in
a block now.
=> thread_pool: change severity of "full queue" msg from error to info

lib/airbrake-ruby/time_truncate.rb, spec/time_truncate_spec.rb
`time` argument in `Airbrake::TimeTruncate` is now a Float in Rails 7.0.0 unlike an instance of `Time` in Rails 6.x or earlier.
Relates to airbrake/airbrake#1205
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
=> Workaround in TimeTruncate with Rails 7.0.0

CHANGELOG.md, lib/airbrake-ruby/filters/git_repository_filter.rb, spec/filters/git_repository_filter_spec.rb
Fixes https://github.com/airbrake/airbrake-ruby/issues/680
(Errno::EAGAIN: Resource temporarily unavailable with falcon)
=> airbrake-ruby/filters/git_repository_filter: fix Errno::EAGAIN

CHANGELOG.md, lib/airbrake-ruby/config/processor.rb, spec/config/processor_spec.rb
Fixes #679
(Remote configuration is polled for despite ignore_environments)
=> config: don't poll remote config if the current env is ignored

spec/notice_spec.rb
There is unwanted `context` in the "happens" spec. Probably a bad copy-paste.
=> spec/notice: simplify spec

CHANGELOG.md, lib/airbrake-ruby/nested_exception.rb, lib/airbrake-ruby/notice.rb, spec/nested_exception_spec.rb, spec/notice_spec.rb
Addresses https://github.com/airbrake/airbrake/issues/1230
Error highlighting is not good for our grouping. Therefore, we need to strip it from
the error message prior to reporting to Airbrake. The unstripped version of the
error is now attached to `context/error_message`.
=> nested_exception: add support for Ruby 3.1 error with highlighting

CHANGELOG.md, lib/airbrake-ruby/nested_exception.rb, spec/nested_exception_spec.rb
Fixes #697
(Exceptions with nil for message cause error in v6.1.1)
=> nested_exception: don't crash when the exception's message is nil

README.md, lib/airbrake-ruby.rb, lib/airbrake-ruby/async_sender.rb, lib/airbrake-ruby/backlog.rb, lib/airbrake-ruby/config.rb, lib/airbrake-ruby/notice_notifier.rb, lib/airbrake-ruby/performance_notifier.rb, lib/airbrake-ruby/response.rb, lib/airbrake-ruby/sync_sender.rb, spec/backlog_spec.rb, spec/config_spec.rb, spec/notice_notifier_spec.rb, spec/response_spec.rb, spec/sync_sender_spec.rb
The Backlog class accepts notices and APM events and synchronously sends them in
the background at regular intervals (2 minutes).
The notices that it accepts are those that have failed to be sent due to network
issues or Airbrake servers struggling. If the second attempt fails, then such
data is discarded forever.
The maximum backlog size is 100. If we cannot add to the backlog anymore, the
item would be skipped and an error would be logged.
=> Add Backlog

CHANGELOG.md, lib/airbrake-ruby/config.rb, spec/config_spec.rb
Fixes #710
(Set error_host and apm_host to host by default)
=> config: deprecate 'host'

lib/airbrake-ruby/thread_pool.rb, spec/thread_pool_spec.rb
Enclosing the ThreadGroup has caused issues for anyone using version 0.3.1 of the timeout gem. @thompiler and I were able to replicate the issue by running a rails 7.0.4 app with ruby version 3.2.1 and the timeout gem at version 0.3.1 `timeout, '= 0.3.1'` in the Gemfile. It was also important to run the rails server with `WEB_CONCURRENCY=3`.
```
WEB_CONCURRENCY=3 bin/rails s
```
Then watch the airbrake logs you may need to enable this in your airbrake.rb initializer. Any Net::HTTP request will trigger a timeout on the enclosed ThreadGroup and cause an issue. This could be sending an Airbrake notice, performance data or fetching the remote config.
=> Do not enclose the worker ThreadGroup

CHANGELOG.md, lib/airbrake-ruby/version.rb
- Fixed ruby/timeout issue by avoiding `ThreadGroup#enclose` ([#714](https://github.com/airbrake/airbrake-ruby/pull/714))
- Deprecated the `host` option in favor of `error_host` ([#711](https://github.com/airbrake/airbrake-ruby/pull/711))
- Updated YARD dependency to work with most recent ruby ([#715](https://github.com/airbrake/airbrake-ruby/pull/715))
- Improved a spec that was depending on the GitHub actions git setup ([#716](https://github.com/airbrake/airbrake-ruby/pull/716))
=> Release v6.2.1

lib/airbrake-ruby/deploy_notifier.rb
When using deployment tracking via `Airbrake.notify_deploy` we always get a deprecation warning:
W, [2023-07-07T14:42:40.940088 #3280]  WARN -- : **Airbrake: the 'host' option is deprecated. Use 'error_host' instead
This commit uses `error_host` instead, so no deprecation warning is triggered.
=> Use #error_host instead of #host to avoid triggering a deprecation warning with deployment tracking

CHANGELOG.md, lib/airbrake-ruby/version.rb
- Use `error_host` instead of `host` to avoid triggering a deprecation warning with deployment tracking ([#721](https://github.com/airbrake/airbrake-ruby/pull/721))
- release: https://github.com/airbrake/airbrake-ruby/releases/tag/v6.2.2
=> Release v6.2.2
